FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o controller ./cmd/controller

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/controller .
COPY --from=builder /app/web ./web

CMD ["./controller"]

